In [1]:
# Download libraries
!pip3 install azure-storage-blob # Microoft Azure
!pip3 install pyarrow # Apache Arrow

Collecting azure-storage-blob
  Downloading azure_storage_blob-12.19.1-py3-none-any.whl (394 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 394.5/394.5 kB 5.8 MB/s eta 0:00:00 MB/s eta 0:00:01
Collecting azure-core<2.0.0,>=1.28.0
  Downloading azure_core-1.30.1-py3-none-any.whl (193 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.4/193.4 kB 17.3 MB/s eta 0:00:00
Collecting cryptography>=2.1.4
  Downloading cryptography-42.0.5-cp39-abi3-macosx_10_12_universal2.whl (5.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.9/5.9 MB 30.1 MB/s eta 0:00:0031m28.2 MB/s eta 0:00:01
Requirement already satisfied: typing-extensions>=4.3.0 in /Users/wasikulislam/Library/Python/3.11/lib/python/site-packages (from azure-storage-blob) (4.10.0)
Collecting isodate>=0.6.1
  Downloading isodate-0.6.1-py2.py3-none-any.whl (41 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.7/41.7 kB 4.9 MB/s eta 0:00:00
Collecting requests>=2.21.0
  Downloading requests-2.31.0-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.6/62.6 kB 9.0 MB/s eta 0:00:00
Requirement already satisfied: six>=1.11.0 in /Users/wasikulislam/Library/Python/3.11/lib/python/site-packages (from azure-core<2.0.0,>=1.28.0->azure-storage-blob) (1.16.0)
Collecting cffi>=1.12
  Downloading cffi-1.16.0-cp311-cp311-macosx_11_0_arm64.whl (176 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 176.7/176.7 kB 19.1 MB/s eta 0:00:00
Collecting pycparser
  Downloading pycparser-2.22-py3-none-any.whl (117 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.6/117.6 kB 10.3 MB/s eta 0:00:00
Collecting charset-normalizer<4,>=2
  Downloading charset_normalizer-3.3.2-cp311-cp311-macosx_11_0_arm64.whl (118 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.0/119.0 kB 12.7 MB/s eta 0:00:00
Collecting idna<4,>=2.5
  Downloading idna-3.7-py3-none-any.whl (66 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.8/66.8 kB 8.9 MB/s eta 0:00:00
Collecting urllib3<3,>=1.21.1
  Downloading urllib3-2.2.1-py3-none-any.whl (121 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.1/121.1 kB 15.1 MB/s eta 0:00:00
Collecting certifi>=2017.4.17
  Downloading certifi-2024.2.2-py3-none-any.whl (163 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 163.8/163.8 kB 13.3 MB/s eta 0:00:00
Installing collected packages: urllib3, pycparser, isodate, idna, charset-normalizer, certifi, requests, cffi, cryptography, azure-core, azure-storage-blob
Successfully installed azure-core-1.30.1 azure-storage-blob-12.19.1 certifi-2024.2.2 cffi-1.16.0 charset-normalizer-3.3.2 cryptography-42.0.5 idna-3.7 isodate-0.6.1 pycparser-2.22 requests-2.31.0 urllib3-2.2.1

[notice] A new release of pip available: 22.3 -> 24.0
[notice] To update, run: pip3 install --upgrade pip
Collecting pyarrow
  Downloading pyarrow-15.0.2-cp311-cp311-macosx_11_0_arm64.whl (24.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.2/24.2 MB 36.8 MB/s eta 0:00:00m eta 0:00:010:01:01
Collecting numpy<2,>=1.16.6
  Downloading numpy-1.26.4-cp311-cp311-macosx_11_0_arm64.whl (14.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.0/14.0 MB 34.5 MB/s eta 0:00:00m eta 0:00:01[36m0:00:01
Installing collected packages: numpy, pyarrow
Successfully installed numpy-1.26.4 pyarrow-15.0.2

[notice] A new release of pip available: 22.3 -> 24.0
[notice] To update, run: pip3 install --upgrade pip

In [2]:
# Import libraries
from io import StringIO
import numpy as np
import pandas as pd
import json
import requests
from azure.storage.blob import BlobServiceClient, BlobClient, ContainerClient

In [3]:
#URLs for each borough's Excel file

URL_manhattan = "https://www.nyc.gov/assets/finance/downloads/pdf/rolling_sales/rollingsales_manhattan.xlsx"
URL_bronx = "https://www.nyc.gov/assets/finance/downloads/pdf/rolling_sales/rollingsales_bronx.xlsx"
URL_brooklyn = "https://www.nyc.gov/assets/finance/downloads/pdf/rolling_sales/rollingsales_brooklyn.xlsx"
URL_queens = "https://www.nyc.gov/assets/finance/downloads/pdf/rolling_sales/rollingsales_queens.xlsx"
URL_statenisland = "https://www.nyc.gov/assets/finance/downloads/pdf/rolling_sales/rollingsales_statenisland.xlsx"

# Loading each Excel file into a separate dataframe
df_manhattan = pd.read_excel(URL_manhattan)
df_bronx = pd.read_excel(URL_bronx)
df_brooklyn = pd.read_excel(URL_brooklyn)
df_queens = pd.read_excel(URL_queens)
df_statenisland = pd.read_excel(URL_statenisland)

# Display information about each dataframe
print("Manhattan DataFrame Info:")
print(df_manhattan.info())
print(df_manhattan.head())

print("Bronx DataFrame Info:")
print(df_bronx.info())
print(df_bronx.head())

print("Brooklyn DataFrame Info:")
print(df_brooklyn.info())
print(df_brooklyn.head())

print("Queens DataFrame Info:")
print(df_queens.info())
print(df_queens.head())

print("Staten Island DataFrame Info:")
print(df_statenisland.info())
print(df_statenisland.head())

Manhattan DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16788 entries, 0 to 16787
Data columns (total 21 columns):
 #   Column                                                               Non-Null Count  Dtype
---  ------                                                               --------------  -----
 0   Manhattan Rolling Sales.  All Sales From March 2023 - February 2024  16788 non-null  object
 1   Unnamed: 1                                                           16785 non-null  object
 2   Unnamed: 2                                                           16785 non-null  object
 3   Unnamed: 3                                                           16770 non-null  object
 4   Unnamed: 4                                                           16785 non-null  object
 5   Unnamed: 5                                                           16785 non-null  object
 6   Unnamed: 6                                                           1 non-null      object
 7   Unnamed: 7                                                           16770 non-null  object
 8   Unnamed: 8                                                           16785 non-null  object
 9   Unnamed: 9                                                           7741 non-null   object
 10  Unnamed: 10                                                          16785 non-null  object
 11  Unnamed: 11                                                          8667 non-null   object
 12  Unnamed: 12                                                          2161 non-null   object
 13  Unnamed: 13                                                          9290 non-null   object
 14  Unnamed: 14                                                          1538 non-null   object
 15  Unnamed: 15                                                          1538 non-null   object
 16  Unnamed: 16                                                          15032 non-null  object
 17  Unnamed: 17                                                          16785 non-null  object
 18  Unnamed: 18                                                          16785 non-null  object
 19  PTS Sales Data as of 03/12/2024                                      16785 non-null  object
 20  Unnamed: 20                                                          16785 non-null  object
dtypes: object(21)
memory usage: 2.7+ MB
None
  Manhattan Rolling Sales.  All Sales From March 2023 - February 2024  \
0  For sales prior to the Final Roll, Neighborhoo...
1  Building Class Category is based on Building C...
2  Note: Condominium and cooperative sales are on...
3                                            BOROUGH
4                                                  1

      Unnamed: 1               Unnamed: 2            Unnamed: 3 Unnamed: 4  \
0            NaN                      NaN                   NaN        NaN
1            NaN                      NaN                   NaN        NaN
2            NaN                      NaN                   NaN        NaN
3   NEIGHBORHOOD  BUILDING CLASS CATEGORY  TAX CLASS AT PRESENT      BLOCK
4  ALPHABET CITY  02 TWO FAMILY DWELLINGS                     1        386

  Unnamed: 5 Unnamed: 6                 Unnamed: 7   Unnamed: 8  \
0        NaN        NaN                        NaN          NaN
1        NaN        NaN                        NaN          NaN
2        NaN        NaN                        NaN          NaN
3        LOT   EASEMENT  BUILDING CLASS AT PRESENT      ADDRESS
4          7        NaN                         S2  49 AVENUE B

         Unnamed: 9  ...        Unnamed: 11       Unnamed: 12  Unnamed: 13  \
0               NaN  ...                NaN               NaN          NaN
1               NaN  ...                NaN               NaN          NaN
2               NaN  ...                NaN               NaN          NaN
3  APARTMENT NUMBER  ...  RESIDENTIAL UNITS  COMMERCIAL UNITS  TOTAL UNITS
4               NaN  ...                  2                 1            3

        Unnamed: 14        Unnamed: 15 Unnamed: 16                Unnamed: 17  \
0               NaN                NaN         NaN                        NaN
1               NaN                NaN         NaN                        NaN
2               NaN                NaN         NaN                        NaN
3  LAND SQUARE FEET  GROSS SQUARE FEET  YEAR BUILT  TAX CLASS AT TIME OF SALE
4              1725               2304        1880                          1

                      Unnamed: 18 PTS Sales Data as of 03/12/2024  \
0                             NaN                             NaN
1                             NaN                             NaN
2                             NaN                             NaN
3  BUILDING CLASS AT TIME OF SALE                      SALE PRICE
4                              S2                               0

           Unnamed: 20
0                  NaN
1                  NaN
2                  NaN
3            SALE DATE
4  2023-11-02 00:00:00

[5 rows x 21 columns]
Bronx DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5749 entries, 0 to 5748
Data columns (total 21 columns):
 #   Column                                                           Non-Null Count  Dtype
---  ------                                                           --------------  -----
 0   Bronx Rolling Sales.  All Sales From March 2023 - February 2024  5749 non-null   object
 1   Unnamed: 1                                                       5746 non-null   object
 2   Unnamed: 2                                                       5746 non-null   object
 3   Unnamed: 3                                                       5746 non-null   object
 4   Unnamed: 4                                                       5746 non-null   object
 5   Unnamed: 5                                                       5746 non-null   object
 6   Unnamed: 6                                                       1 non-null      object
 7   Unnamed: 7                                                       5746 non-null   object
 8   Unnamed: 8                                                       5746 non-null   object
 9   Unnamed: 9                                                       527 non-null    object
 10  Unnamed: 10                                                      5746 non-null   object
 11  Unnamed: 11                                                      4730 non-null   object
 12  Unnamed: 12                                                      4266 non-null   object
 13  Unnamed: 13                                                      4766 non-null   object
 14  Unnamed: 14                                                      4230 non-null   object
 15  Unnamed: 15                                                      4230 non-null   object
 16  Unnamed: 16                                                      5152 non-null   object
 17  Unnamed: 17                                                      5746 non-null   object
 18  Unnamed: 18                                                      5746 non-null   object
 19  PTS Sales Data as of 03/12/2024                                  5746 non-null   object
 20  Unnamed: 20                                                      5746 non-null   object
dtypes: object(21)
memory usage: 943.3+ KB
None
  Bronx Rolling Sales.  All Sales From March 2023 - February 2024  \
0  For sales prior to the Final Roll, Neighborhoo...
1  Building Class Category is based on Building C...
2  Note: Condominium and cooperative sales are on...
3                                            BOROUGH
4                                                  2

     Unnamed: 1               Unnamed: 2            Unnamed: 3 Unnamed: 4  \
0           NaN                      NaN                   NaN        NaN
1           NaN                      NaN                   NaN        NaN
2           NaN                      NaN                   NaN        NaN
3  NEIGHBORHOOD  BUILDING CLASS CATEGORY  TAX CLASS AT PRESENT      BLOCK
4      BATHGATE  01 ONE FAMILY DWELLINGS                     1       3030

  Unnamed: 5 Unnamed: 6                 Unnamed: 7        Unnamed: 8  \
0        NaN        NaN                        NaN               NaN
1        NaN        NaN                        NaN               NaN
2        NaN        NaN                        NaN               NaN
3        LOT   EASEMENT  BUILDING CLASS AT PRESENT           ADDRESS
4         66        NaN                         A1  4453 PARK AVENUE

         Unnamed: 9  ...        Unnamed: 11       Unnamed: 12  Unnamed: 13  \
0               NaN  ...                NaN               NaN          NaN
1               NaN  ...                NaN               NaN          NaN
2               NaN  ...                NaN               NaN          NaN
3  APARTMENT NUMBER  ...  RESIDENTIAL UNITS  COMMERCIAL UNITS  TOTAL UNITS
4               NaN  ...                  1                 0            1

        Unnamed: 14        Unnamed: 15 Unnamed: 16                Unnamed: 17  \
0               NaN                NaN         NaN                        NaN
1               NaN                NaN         NaN                        NaN
2               NaN                NaN         NaN                        NaN
3  LAND SQUARE FEET  GROSS SQUARE FEET  YEAR BUILT  TAX CLASS AT TIME OF SALE
4              1646               1497        1899                          1

                      Unnamed: 18 PTS Sales Data as of 03/12/2024  \
0                             NaN                             NaN
1                             NaN                             NaN
2                             NaN                             NaN
3  BUILDING CLASS AT TIME OF SALE                      SALE PRICE
4                              A1                          215000

           Unnamed: 20
0                  NaN
1                  NaN
2                  NaN
3            SALE DATE
4  2023-04-18 00:00:00

[5 rows x 21 columns]
Brooklyn DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21156 entries, 0 to 21155
Data columns (total 21 columns):
 #   Column                                                              Non-Null Count  Dtype
---  ------                                                              --------------  -----
 0   Brooklyn Rolling Sales.  All Sales From March 2023 - February 2024  21156 non-null  object
 1   Unnamed: 1                                                          21153 non-null  object
 2   Unnamed: 2                                                          21153 non-null  object
 3   Unnamed: 3                                                          21113 non-null  object
 4   Unnamed: 4                                                          21153 non-null  object
 5   Unnamed: 5                                                          21153 non-null  object
 6   Unnamed: 6                                                          1 non-null      object
 7   Unnamed: 7                                                          21113 non-null  object
 8   Unnamed: 8                                                          21153 non-null  object
 9   Unnamed: 9                                                          5372 non-null   object
 10  Unnamed: 10                                                         21152 non-null  object
 11  Unnamed: 11                                                         17482 non-null  object
 12  Unnamed: 12                                                         14174 non-null  object
 13  Unnamed: 13                                                         18504 non-null  object
 14  Unnamed: 14                                                         13152 non-null  object
 15  Unnamed: 15                                                         13152 non-null  object
 16  Unnamed: 16                                                         19842 non-null  object
 17  Unnamed: 17                                                         21153 non-null  object
 18  Unnamed: 18                                                         21153 non-null  object
 19  PTS Sales Data as of 03/12/2024                                     21153 non-null  object
 20  Unnamed: 20                                                         21153 non-null  object
dtypes: object(21)
memory usage: 3.4+ MB
None
  Brooklyn Rolling Sales.  All Sales From March 2023 - February 2024  \
0  For sales prior to the Final Roll, Neighborhoo...
1  Building Class Category is based on Building C...
2  Note: Condominium and cooperative sales are on...
3                                            BOROUGH
4                                                  3

     Unnamed: 1               Unnamed: 2            Unnamed: 3 Unnamed: 4  \
0           NaN                      NaN                   NaN        NaN
1           NaN                      NaN                   NaN        NaN
2           NaN                      NaN                   NaN        NaN
3  NEIGHBORHOOD  BUILDING CLASS CATEGORY  TAX CLASS AT PRESENT      BLOCK
4    BATH BEACH  01 ONE FAMILY DWELLINGS                     1       6360

  Unnamed: 5 Unnamed: 6                 Unnamed: 7          Unnamed: 8  \
0        NaN        NaN                        NaN                 NaN
1        NaN        NaN                        NaN                 NaN
2        NaN        NaN                        NaN                 NaN
3        LOT   EASEMENT  BUILDING CLASS AT PRESENT             ADDRESS
4         56        NaN                         A5  30 BAY 10TH STREET

         Unnamed: 9  ...        Unnamed: 11       Unnamed: 12  Unnamed: 13  \
0               NaN  ...                NaN               NaN          NaN
1               NaN  ...                NaN               NaN          NaN
2               NaN  ...                NaN               NaN          NaN
3  APARTMENT NUMBER  ...  RESIDENTIAL UNITS  COMMERCIAL UNITS  TOTAL UNITS
4               NaN  ...                  1                 0            1

        Unnamed: 14        Unnamed: 15 Unnamed: 16                Unnamed: 17  \
0               NaN                NaN         NaN                        NaN
1               NaN                NaN         NaN                        NaN
2               NaN                NaN         NaN                        NaN
3  LAND SQUARE FEET  GROSS SQUARE FEET  YEAR BUILT  TAX CLASS AT TIME OF SALE
4              1547               1428        1930                          1

                      Unnamed: 18 PTS Sales Data as of 03/12/2024  \
0                             NaN                             NaN
1                             NaN                             NaN
2                             NaN                             NaN
3  BUILDING CLASS AT TIME OF SALE                      SALE PRICE
4                              A5                               0

           Unnamed: 20
0                  NaN
1                  NaN
2                  NaN
3            SALE DATE
4  2023-07-31 00:00:00

[5 rows x 21 columns]
Queens DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23500 entries, 0 to 23499
Data columns (total 21 columns):
 #   Column                                                            Non-Null Count  Dtype
---  ------                                                            --------------  -----
 0   Queens Rolling Sales.  All Sales From March 2023 - February 2024  23500 non-null  object
 1   Unnamed: 1                                                        23497 non-null  object
 2   Unnamed: 2                                                        23497 non-null  object
 3   Unnamed: 3                                                        23492 non-null  object
 4   Unnamed: 4                                                        23497 non-null  object
 5   Unnamed: 5                                                        23497 non-null  object
 6   Unnamed: 6                                                        1 non-null      object
 7   Unnamed: 7                                                        23492 non-null  object
 8   Unnamed: 8                                                        23497 non-null  object
 9   Unnamed: 9                                                        3542 non-null   object
 10  Unnamed: 10                                                       23497 non-null  object
 11  Unnamed: 11                                                       18235 non-null  object
 12  Unnamed: 12                                                       15950 non-null  object
 13  Unnamed: 13                                                       18860 non-null  object
 14  Unnamed: 14                                                       15325 non-null  object
 15  Unnamed: 15                                                       15325 non-null  object
 16  Unnamed: 16                                                       22567 non-null  object
 17  Unnamed: 17                                                       23497 non-null  object
 18  Unnamed: 18                                                       23497 non-null  object
 19  PTS Sales Data as of 03/12/2024                                   23497 non-null  object
 20  Unnamed: 20                                                       23497 non-null  object
dtypes: object(21)
memory usage: 3.8+ MB
None
  Queens Rolling Sales.  All Sales From March 2023 - February 2024  \
0  For sales prior to the Final Roll, Neighborhoo...
1  Building Class Category is based on Building C...
2  Note: Condominium and cooperative sales are on...
3                                            BOROUGH
4                                                  4

     Unnamed: 1                 Unnamed: 2            Unnamed: 3 Unnamed: 4  \
0           NaN                        NaN                   NaN        NaN
1           NaN                        NaN                   NaN        NaN
2           NaN                        NaN                   NaN        NaN
3  NEIGHBORHOOD    BUILDING CLASS CATEGORY  TAX CLASS AT PRESENT      BLOCK
4   AIRPORT JFK  31 COMMERCIAL VACANT LAND                     4      14260

  Unnamed: 5 Unnamed: 6                 Unnamed: 7         Unnamed: 8  \
0        NaN        NaN                        NaN                NaN
1        NaN        NaN                        NaN                NaN
2        NaN        NaN                        NaN                NaN
3        LOT   EASEMENT  BUILDING CLASS AT PRESENT            ADDRESS
4         80        NaN                         E1  N/A ROCKAWAY BLVD

         Unnamed: 9  ...        Unnamed: 11       Unnamed: 12  Unnamed: 13  \
0               NaN  ...                NaN               NaN          NaN
1               NaN  ...                NaN               NaN          NaN
2               NaN  ...                NaN               NaN          NaN
3  APARTMENT NUMBER  ...  RESIDENTIAL UNITS  COMMERCIAL UNITS  TOTAL UNITS
4               NaN  ...                  0                 1            1

        Unnamed: 14        Unnamed: 15 Unnamed: 16                Unnamed: 17  \
0               NaN                NaN         NaN                        NaN
1               NaN                NaN         NaN                        NaN
2               NaN                NaN         NaN                        NaN
3  LAND SQUARE FEET  GROSS SQUARE FEET  YEAR BUILT  TAX CLASS AT TIME OF SALE
4            268092                  0        2023                          4

                      Unnamed: 18 PTS Sales Data as of 03/12/2024  \
0                             NaN                             NaN
1                             NaN                             NaN
2                             NaN                             NaN
3  BUILDING CLASS AT TIME OF SALE                      SALE PRICE